export const STANDARD_TOP_OF_SVG = 0;
export const STANDARD_TOP_OF_BLOCK = 4;
export const STANDARD_BOTTOM_OF_BLOCK = 52;
export const STANDARD_TOP_OF_DIVET = 12;
export const STANDARD_BOTTOM_OF_DIVET = 60;
export const STANDARD_BOTTOM_OF_SVG = 64;

export const CBLOCK_TOP_OF_SVG = 0;
export const CBLOCK_TOP_OF_BLOCK = 4;
export const CBLOCK_BOTTOM_OF_DIVET1 = 12;
export const CBLOCK_BOTTOM_OF_BLOCK1 = 44;
export const CBLOCK_BOTTOM_OF_DIVET2 = 52;
export const CBLOCK_TOP_OF_BLOCK2 = 92;
export const CBLOCK_BOTTOM_OF_DIVET3 = 108;
export const CBLOCK_BOTTOM_OF_BLOCK2 = 132;
export const CBLOCK_BOTTOM_OF_DIVET4 = 140;
export const CBLOCK_BOTTOM_OF_SVG = 144;
export const CBLOCK_HEIGHT_OF_EXTRA_INTERNAL_BLOCK = CBLOCK_TOP_OF_BLOCK2 - CBLOCK_BOTTOM_OF_BLOCK1;
export const CBLOCK_XSTART_OF_INDENT = 20;

export const STARTBLOCK_TOP_OF_SVG = 0;
export const STARTBLOCK_TOP_OF_CURVE = 4;
export const STARTBLOCK_TOP_OF_BLOCK = 21;
export const STARTBLOCK_BOTTOM_OF_BLOCK = 69;
export const STARTBLOCK_BOTTOM_OF_DIVET = 77;
export const STARTBLOCK_BOTTOM_OF_SVG = 81;
export const STARTBLOCK_DEFAULT_WIDTH_OF_TOP_HORIZONTAL = 58;
export const STARTBLOCK_DEFAULT_WIDTH_OF_BOTTOM_HORIZONTAL = 102;
